version: '2.2'

networks:
  backend:

volumes:
  datavolume:
  staticvolume:

services:
  web:
    build: ./web
    restart: always
    container_name: web
    volumes:
      - staticvolume:/usr/src/app/public
    expose:
      - '3000'
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    build: ./db
    restart: always
    expose:
      - '27017'
    healthcheck:
      test: echo 'db.stats().ok'
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - datavolume:/data/db
    networks:
      - backend
    user: mongodb

  nginx:
    restart: always
    build: ./nginx/
    tty: false
    ports:
      - "80:80"
    volumes:
      - staticvolume:/www/public
      - staticvolume:/usr/src/app
    links:
      - web:web
    depends_on:
      - web
    networks:
      - backend
